### ISSUE TITLE
Exception while parsing message type 

### ISSUE THREAD

**Issue by hdghg** [hdghg/goatway#1]
```
08:09:14.014 [t Reader (8)] WARN  o.j.s.AbstractXMPPConnection:1192 - Connection closed with error
java.lang.IllegalArgumentException: No enum constant org.jivesoftware.smack.packet.Message.Type.replyroom
        at java.lang.Enum.valueOf(Enum.java:236)
        at org.jivesoftware.smack.packet.Message$Type.valueOf(Message.java:607)
        at org.jivesoftware.smack.packet.Message$Type.fromString(Message.java:644)
        at org.jivesoftware.smack.util.PacketParserUtils.parseMessage(PacketParserUtils.java:229)
        at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:151)
        at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:955)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$500(XMPPTCPConnection.java:140)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1001)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:956)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:971)
```

**Comment by hdghg** [comment]
08:09:14.014 [ Reader (13)] WARN  o.j.s.AbstractXMPPConnection:1192 - Connection closed with error
    java.lang.IllegalArgumentException: No enum constant org.jivesoftware.smack.packet.Message.Type.replyroom
            at java.lang.Enum.valueOf(Enum.java:236)
            at org.jivesoftware.smack.packet.Message$Type.valueOf(Message.java:607)
            at org.jivesoftware.smack.packet.Message$Type.fromString(Message.java:644)
            at org.jivesoftware.smack.util.PacketParserUtils.parseMessage(PacketParserUtils.java:229)
            at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:151)
            at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:955)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$500(XMPPTCPConnection.java:140)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1001)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:956)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:971)
            at java.lang.Thread.run(Thread.java:745)
