### ISSUE TITLE
Exception while sending message to tg

### ISSUE THREAD

**Issue by hdghg** [hdghg/goatway#4]
```
04:18:20.020 ERROR g.c.xmpp.sender - Exception while sending message to telegram
java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:635)
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:934)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at clj_http.lite.core$request.invokeStatic(core.clj:76)
    at clj_http.lite.core$request.invoke(core.clj:42)
    at clojure.lang.Var.invoke(Var.java:379)
    at clj_http.lite.client$wrap_query_params$fn__4353.invoke(client.clj:163)
    at clj_http.lite.client$wrap_user_info$fn__4363.invoke(client.clj:190)
    at clj_http.lite.client$wrap_url$fn__4378.invoke(client.clj:212)
    at clj_http.lite.client$wrap_redirects$fn__4299.invoke(client.clj:46)
    at clj_http.lite.client$wrap_decompression$fn__4306.invoke(client.clj:62)
    at clj_http.lite.client$wrap_input_coercion$fn__4321.invoke(client.clj:114)
    at clj_http.lite.client$wrap_output_coercion$fn__4312.invoke(client.clj:71)
    at clj_http.lite.client$wrap_exceptions$fn__4288.invoke(client.clj:32)
    at clj_http.lite.client$wrap_basic_auth$fn__4358.invoke(client.clj:180)
    at clj_http.lite.client$wrap_accept$fn__4333.invoke(client.clj:134)
    at clj_http.lite.client$wrap_accept_encoding$fn__4339.invoke(client.clj:145)
    at clj_http.lite.client$wrap_content_type$fn__4328.invoke(client.clj:126)
    at clj_http.lite.client$wrap_form_params$fn__4373.invoke(client.clj:207)
    at clj_http.lite.client$wrap_method$fn__4368.invoke(client.clj:195)
    at clj_http.lite.client$wrap_unknown_host$fn__4383.invoke(client.clj:218)
    at clj_http.lite.client$get.invokeStatic(client.clj:271)
    at clj_http.lite.client$get.doInvoke(client.clj:268)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at gram_api.ll$call_api_.invokeStatic(ll.clj:7)
    at gram_api.ll$call_api_.invoke(ll.clj:6)
    at gram_api.ll$send_message.invokeStatic(ll.clj:13)
    at gram_api.ll$send_message.invoke(ll.clj:12)
    at gram_api.hl$send_message_cycled.invokeStatic(hl.clj:48)
    at gram_api.hl$send_message_cycled.invoke(hl.clj:40)
    at goatway.channels.xmpp.sender$sender_chan$fn__13504$state_machine__10094__auto____13505$fn__13507.invoke(sender.clj:20)
    at goatway.channels.xmpp.sender$sender_chan$fn__13504$state_machine__10094__auto____13505.invoke(sender.clj:20)
    at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:1012)
    at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:1011)
    at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:1016)
    at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:1014)
    at clojure.core.async.impl.ioc_macros$take_BANG_$fn__10110.invoke(ioc_macros.clj:1025)
    at clojure.core.async.impl.channels.ManyToManyChannel$fn__5106.invoke(channels.clj:135)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by hdghg** [comment]
Project is closed
